# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
run-name: Build epc-qr-generator
on:
  push:
    branches: [ "github_actions" ]

permissions: 
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Install packages
      run: |
        sudo apt install -y git python3 python3-venv gettext binutils python3-tk
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build python app with pyinstaller
      run: |
        source .venv/bin/activate
        ./build_executable.linux.sh
        ls -la dist/
